"use client";

import { ArrowDown, ArrowUp, ArrowUpRight, BookOpen, Check, ChevronRight, ExternalLink, FilePenLine, LayoutDashboard, LogOut, MessageSquareText, Plus, Save, Settings, Sparkles, Trash2, Users } from "lucide-react";
import { useMemo, useState } from "react";
import { Logo } from "@/components/Logo";
import { BlogPost, CmsBlock, editablePageLabels, KnowledgeItem, Lead, pageFor, PageKey, SiteContent } from "@/lib/site-content";

type Section = "pages" | "blog" | "knowledge" | "leads";
const icons = { hero: Sparkles, insurance: Settings, services: LayoutDashboard, story: BookOpen, ecosystem: ChevronRight, cta: ArrowUpRight, "rich-text": FilePenLine };

export function AdminDashboard({ initialContent, initialLeads }: { initialContent: SiteContent; initialLeads: Lead[] }) {
  const [content, setContent] = useState(initialContent);
  const [selected, setSelected] = useState<PageKey>("home");
  const [section, setSection] = useState<Section>("pages");
  const [blockIndex, setBlockIndex] = useState(0);
  const [notice, setNotice] = useState("");
  const [saving, setSaving] = useState(false);
  const page = pageFor(content, selected);
  const block = page.blocks[blockIndex];
  const leads = useMemo(() => initialLeads.slice(0, 30), [initialLeads]);

  function updatePage(field: "title" | "description" | "primaryCta" | "secondaryCta", value: string) {
    setContent((current) => updateSelectedPage(current, selected, { [field]: value })); setNotice("");
  }
  function updateBlock(field: keyof CmsBlock, value: string | boolean) {
    if (!block) return;
    setContent((current) => updateSelectedPage(current, selected, { blocks: page.blocks.map((item, index) => index === blockIndex ? { ...item, [field]: value } : item) })); setNotice("");
  }
  function addBlock() {
    const next: CmsBlock = { id: `block-${selected}-${page.blocks.length + 1}`, type: "rich-text", title: "Nuevo bloque", body: "Escribe aquí el contenido que quieres mostrar.", ctaLabel: "", ctaHref: "", enabled: true };
    setContent((current) => updateSelectedPage(current, selected, { blocks: [...page.blocks, next] })); setBlockIndex(page.blocks.length);
  }
  function moveBlock(direction: -1 | 1) {
    const nextIndex = blockIndex + direction; if (nextIndex < 0 || nextIndex >= page.blocks.length) return;
    const blocks = [...page.blocks]; [blocks[blockIndex], blocks[nextIndex]] = [blocks[nextIndex], blocks[blockIndex]];
    setContent((current) => updateSelectedPage(current, selected, { blocks })); setBlockIndex(nextIndex);
  }
  function deleteBlock() { if (!block || page.blocks.length === 1) return; setContent((current) => updateSelectedPage(current, selected, { blocks: page.blocks.filter((_, i) => i !== blockIndex) })); setBlockIndex(Math.max(0, blockIndex - 1)); }
  function addPost() { const number = content.blog.length + 1; const id = `post-${number}`; const post: BlogPost = { id, title: "Nuevo artículo", slug: `nuevo-articulo-${number}`, excerpt: "Un resumen breve que invita a leer.", body: "Escribe el contenido del artículo aquí.", category: "J R Consulting", published: false, publishedAt: "2026-07-22T00:00:00.000Z" }; setContent((current) => ({ ...current, blog: [post, ...current.blog] })); }
  function updatePost(id: string, field: keyof BlogPost, value: string | boolean) { setContent((current) => ({ ...current, blog: current.blog.map((post) => post.id === id ? { ...post, [field]: value } : post) })); }
  function addKnowledge() { const item: KnowledgeItem = { id: `knowledge-${content.knowledge.length + 1}`, topic: "General", question: "Nueva pregunta", answer: "Redacta la respuesta que el agente debe utilizar." }; setContent((current) => ({ ...current, knowledge: [item, ...current.knowledge] })); }
  function updateKnowledge(id: string, field: keyof KnowledgeItem, value: string) { setContent((current) => ({ ...current, knowledge: current.knowledge.map((item) => item.id === id ? { ...item, [field]: value } : item) })); }
  async function save() { setSaving(true); setNotice(""); try { const response = await fetch("/api/admin/content", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(content) }); const data = await response.json(); setNotice(response.ok ? `Cambios publicados${data.storage === "local" ? " en modo local" : ""}.` : data.error || "No fue posible guardar."); } catch { setNotice("No se pudo conectar con el servidor."); } finally { setSaving(false); } }
  async function logout() { await fetch("/api/admin/logout", { method: "POST" }); window.location.href = "/admin/login"; }
  const pageUrl = selected === "home" ? "/" : selected === "nosotros" ? "/nosotros" : `/${selected}`;

  return <div className="cms-shell"><aside className="cms-sidebar"><Logo inverted /><nav>
    <button className={section === "pages" ? "is-active" : ""} onClick={() => setSection("pages")}><LayoutDashboard />Páginas</button>
    <button className={section === "blog" ? "is-active" : ""} onClick={() => setSection("blog")}><BookOpen />Blog</button>
    <button className={section === "knowledge" ? "is-active" : ""} onClick={() => setSection("knowledge")}><MessageSquareText />Base de conocimientos</button>
    <button className={section === "leads" ? "is-active" : ""} onClick={() => setSection("leads")}><Users />Leads</button>
  </nav><button className="cms-logout" onClick={logout}><LogOut />Cerrar sesión</button></aside>
  <main className="cms-main"><header className="cms-header"><div><span>J R Consulting</span><h1>{section === "pages" ? `Editar ${editablePageLabels[selected]}` : section === "blog" ? "Blog" : section === "knowledge" ? "Base de conocimientos" : "Prospectos"}</h1></div><div><a className="button button--outline" href={section === "pages" ? pageUrl : section === "blog" ? "/blog" : "/"} target="_blank">Vista previa <ExternalLink size={16} /></a>{section !== "leads" && <button className="button button--primary" onClick={save} disabled={saving}><Save size={16} />{saving ? "Guardando…" : "Publicar cambios"}</button>}</div></header>
  {notice && <p className={notice.startsWith("Cambios") ? "cms-notice" : "cms-error"}>{notice.startsWith("Cambios") && <Check />}{notice}</p>}
  {section === "pages" && <section className="cms-workspace"><div className="cms-list"><div className="cms-list-head"><div><h2>Páginas y bloques</h2><p>El orden es el que verá el visitante.</p></div><select value={selected} onChange={(event) => { setSelected(event.target.value as PageKey); setBlockIndex(0); }}>{Object.entries(editablePageLabels).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select></div><div className="cms-page-fields"><label>Título de página<input value={page.title} onChange={(e) => updatePage("title", e.target.value)} /></label><label>Descripción<textarea rows={3} value={page.description} onChange={(e) => updatePage("description", e.target.value)} /></label></div><div className="cms-list-head cms-block-title"><h2>Bloques</h2><button onClick={addBlock}><Plus size={16} />Agregar bloque</button></div>{page.blocks.map((item, index) => { const Icon = icons[item.type]; return <button key={item.id} className={`cms-block-row${index === blockIndex ? " is-selected" : ""}`} onClick={() => setBlockIndex(index)}><span className="cms-block-icon"><Icon size={18} /></span><span><strong>{item.title}</strong><small>{blockLabel(item.type)} · {item.enabled ? "Visible" : "Oculto"}</small></span><ChevronRight size={17} /></button>; })}</div>
  <div className="cms-inspector">{block ? <><div className="cms-inspector-heading"><span className="cms-block-icon">{(() => { const Icon = icons[block.type]; return <Icon size={18} />; })()}</span><div><h2>{blockLabel(block.type)}</h2><p>Configuración del bloque seleccionado.</p></div></div><label>Tipo de bloque<select value={block.type} onChange={(e) => updateBlock("type", e.target.value)}>{Object.keys(icons).map((type) => <option key={type} value={type}>{blockLabel(type as CmsBlock["type"])}</option>)}</select></label><label>Título<input value={block.title} onChange={(e) => updateBlock("title", e.target.value)} /></label><label>Contenido<textarea rows={7} value={block.body} onChange={(e) => updateBlock("body", e.target.value)} /></label><div className="cms-two-fields"><label>Botón<input value={block.ctaLabel || ""} onChange={(e) => updateBlock("ctaLabel", e.target.value)} /></label><label>Enlace<input value={block.ctaHref || ""} onChange={(e) => updateBlock("ctaHref", e.target.value)} /></label></div><label className="cms-toggle"><input type="checkbox" checked={block.enabled} onChange={(e) => updateBlock("enabled", e.target.checked)} />Mostrar este bloque</label><div className="cms-block-actions"><button onClick={() => moveBlock(-1)} disabled={blockIndex === 0}><ArrowUp size={16} />Subir</button><button onClick={() => moveBlock(1)} disabled={blockIndex === page.blocks.length - 1}><ArrowDown size={16} />Bajar</button><button className="danger" onClick={deleteBlock} disabled={page.blocks.length === 1}><Trash2 size={16} />Eliminar</button></div></> : null}</div></section>}
  {section === "blog" && <section className="cms-stack"><div className="cms-list-head"><div><h2>Artículos</h2><p>Crea borradores, edítalos y publícalos desde aquí.</p></div><button onClick={addPost}><Plus size={16} />Nuevo artículo</button></div>{content.blog.length === 0 && <div className="cms-empty"><BookOpen /><h2>Tu blog está listo.</h2><p>Crea el primer artículo para comenzar a posicionar J R Consulting.</p></div>}{content.blog.map((post) => <article className="cms-editor-card" key={post.id}><div className="cms-card-top"><strong>{post.published ? "Publicado" : "Borrador"}</strong><button onClick={() => setContent((current) => ({ ...current, blog: current.blog.filter((item) => item.id !== post.id) }))}><Trash2 size={16} /></button></div><div className="cms-two-fields"><label>Título<input value={post.title} onChange={(e) => updatePost(post.id, "title", e.target.value)} /></label><label>URL / slug<input value={post.slug} onChange={(e) => updatePost(post.id, "slug", slugify(e.target.value))} /></label></div><label>Resumen<textarea rows={2} value={post.excerpt} onChange={(e) => updatePost(post.id, "excerpt", e.target.value)} /></label><label>Artículo<textarea rows={9} value={post.body} onChange={(e) => updatePost(post.id, "body", e.target.value)} /></label><div className="cms-two-fields"><label>Categoría<input value={post.category} onChange={(e) => updatePost(post.id, "category", e.target.value)} /></label><label className="cms-toggle"><input type="checkbox" checked={post.published} onChange={(e) => updatePost(post.id, "published", e.target.checked)} />Publicar artículo</label></div></article>)}</section>}
  {section === "knowledge" && <section className="cms-stack"><div className="cms-list-head"><div><h2>Conocimiento del agente</h2><p>Estas respuestas orientan al asistente virtual. Actualízalas con información real.</p></div><button onClick={addKnowledge}><Plus size={16} />Nueva respuesta</button></div>{content.knowledge.map((item) => <article className="cms-editor-card" key={item.id}><div className="cms-two-fields"><label>Tema<input value={item.topic} onChange={(e) => updateKnowledge(item.id, "topic", e.target.value)} /></label><button className="cms-delete" onClick={() => setContent((current) => ({ ...current, knowledge: current.knowledge.filter((entry) => entry.id !== item.id) }))}><Trash2 size={16} />Eliminar</button></div><label>Pregunta o intención<input value={item.question} onChange={(e) => updateKnowledge(item.id, "question", e.target.value)} /></label><label>Respuesta aprobada<textarea rows={5} value={item.answer} onChange={(e) => updateKnowledge(item.id, "answer", e.target.value)} /></label></article>)}</section>}
  {section === "leads" && <section className="cms-stack"><div className="cms-list-head"><div><h2>Leads recibidos</h2><p>Solicitudes provenientes de formularios y del asistente virtual.</p></div><span>{leads.length} recientes</span></div>{leads.length ? <div className="cms-lead-table">{leads.map((lead) => <article key={lead.id || lead.email}><div><strong>{lead.name}</strong><small>{lead.email} · {lead.phone}</small></div><span>{lead.service}</span><p>{lead.message}</p><a href={`https://wa.me/52${lead.phone.replace(/\D/g, "")}`} target="_blank" rel="noreferrer">Contactar <ArrowUpRight size={15} /></a></article>)}</div> : <div className="cms-empty"><Users /><h2>Aún no hay solicitudes.</h2><p>Las cotizaciones y conversaciones del asistente aparecerán aquí.</p></div>}</section>}
  </main></div>;
}

function updateSelectedPage(content: SiteContent, selected: PageKey, patch: Partial<ReturnType<typeof pageFor>>): SiteContent { if (selected in content.pages) return { ...content, pages: { ...content.pages, [selected]: { ...content.pages[selected as keyof typeof content.pages], ...patch } } }; return { ...content, [selected]: { ...content[selected as "home" | "aprende" | "research" | "ramx"], ...patch } }; }
function blockLabel(type: CmsBlock["type"]) { return ({ hero: "Hero", insurance: "Seguros destacado", services: "Servicios", story: "Nuestra historia", ecosystem: "Líneas de trabajo", cta: "Llamado a la acción", "rich-text": "Texto libre" })[type]; }
function slugify(value: string) { return value.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g, "").replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, ""); }
